### ISSUE TITLE
Weird issue whenever I change the src of the video

### ISSUE THREAD

**Issue by tarekgabarin** [contently/videojs-annotation-comments#40]
Hello,

My company is currently testing to see whether this plugin suits our needs. We are seeing if it could be used for a tool in which the user can select between different video clips and annotate each one. However, whenever we change the src attribute of the video, this visual bug comes up...

<img width="154" alt="screen shot 2019-01-03 at 4 09 49 pm" src="https://user-images.githubusercontent.com/23179977/50661845-6b284380-0f72-11e9-985c-f3f92fd27cae.png">

Every time I change the src attribute of the video, a duplicate annotation button is added to the video player.
So if I change the src attribute of the video player three times, three notification buttons show up on the controls. 

We are integrating it with AngularJS. And we are doing it all within a single page. Is there anyway we can resolve this issue?

**Comment by jackpope** [comment]
@tarekgabarin any thoughts on this?

**Comment by jackpope** [comment]
@tarekgabarin Let me know if you're still working on this or have any other questions. I'm going to close the issue now but happy to reopen if needed.
