### ISSUE TITLE
jQuery implicit dependency ?

### ISSUE THREAD

**Issue by cdujeu** [contently/videojs-annotation-comments#44]
Hi guys, 
Very nice plugin here! I'd love to try to integrate it, but it seems to me that there is an implicit dependency to jQuery (and we don't want to load jQuery globally). Can you confirm me that, or am i wrong? 
Would it be possible to build a js file that would include $ (or maybe a more lightweight alternative) inside the build scope ? 
Thx!

**Comment by jackpope** [comment]
Thank you @cdujeu! Unfortunately, you are correct that there is an implicit jQuery global dependency here. I hope to some day refactor jQuery out of the plugin completely but it will require some work.

**As for the scoping:**

Quick(?) fix with webpack:

If you are using Webpack to load the module it should be possible to use the [Imports Loader](https://github.com/webpack-contrib/imports-loader) to inject your own local jQuery when importing. It would look something like this, although I haven't tried it myself.

```javascript
const AnnotationComments = require('imports-loader?$=jquery,jQuery=jquery!videojs-annotation-comments');
```

Better fix:

I agree that the build should be smarter about this. When I have some time I can try to rework things to resemble [this](https://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm), where the library will default to `require('jquery')`and fall back to `window.jQuery`. jQuery would become an explicit peer dependency of this project until it can be refactored out.

If you have any ideas on how to best handle this, please let me know. I'll continue to look into solutions as I have time.

**Comment by cdujeu** [comment]
Hey Jack 
Thank you so much for your quick answer. I'm more of a grunt guy, reason why I was trying to use the build version directly ;-). So I'll need some time to digg into webpack (or gulp to rebuild the lib), but i'll definitely will try.
I keep you posted.

**Comment by cdujeu** [comment]
Jack, sorry again for bothering
I'm trying to compile from source to do the jQuery injection, followed the step to npm install, then gulp, then when I run the compile tasks, the "transpile" tasks says no error but just does nothing (nothing in a newly created build folder). Any hints? 
thx!

**Comment by jackpope** [comment]
No worries. Are you running gulp as a global package? For some reason, when I try to run locally through `yarn run` or `npx` the `compile` and `build` commands don't work. It may be due to some incorrect relative paths in the gulp file... not sure at this point.

What does work for me is using the global package. If you follow these commands exactly do you still have trouble? https://github.com/contently/videojs-annotation-comments#develop-and-build

**Comment by cdujeu** [comment]
Yep that exactly what I did, installed gulp globally. 
The css are correctly compiled and appearing inside the build folder, but nothing for js. Is there a way to set a higher level of debug for gulp or a specific build?

**Comment by cdujeu** [comment]
Edit : updating node/npm seems to build js files ! i'll go further and keep you posted, thanks
