### ISSUE TITLE
Drupal integration

### ISSUE THREAD

**Issue by corey-c** [contently/videojs-annotation-comments#45]
I am currently using Video.js for a Drupal 8 site. The owner of the site was wanting the ability for Annotated video. That is what led me to your plugin. 
My question is have you tried adding it to a drupal installation?

**Comment by jackpope** [comment]
Hi @corey-c , I don't have any experience with Drupal but if you can add your own scripts and have a global reference to jQuery, there shouldn't be any trouble.

Let us know if you run into a specific issue.

**Comment by jackpope** [comment]
I'm going to close this since I haven't heard back on any issues. Feel free to reopen if something came up. Thanks
