### ISSUE TITLE
Demo and Documentation page uses unexistent video url

### ISSUE THREAD

**Issue by bestmazzo** [contently/videojs-annotation-comments#59]
This is probably related to 
https://github.com/contently/videojs-annotation-comments/blob/master/docs/_site/index.html#L40
Video source returns 404 😟

**Comment by jackpope** [comment]
Thanks for reporting @bestmazzo . I was clearing out old s3 buckets recently and forgot that these files were sourced in one of them :face_with_head_bandage:
